name: Build and Package macOS App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.3"

      - name: Decode and install certificate
        run: |
          echo "${{ secrets.CERTIFICATE_BASE64 }}" | base64 --decode > /tmp/certificate.p12
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security import /tmp/certificate.p12 -k build.keychain -P ${{ secrets.P12_PASSWORD }} -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain
          security list-keychains -s build.keychain

      - name: Install dependencies
        run: |
          brew install create-dmg

      - name: Build the SwiftUI app with code signing
        run: |
          xcodebuild -scheme Oscar -project Oscar.xcodeproj -configuration Release build CODE_SIGN_IDENTITY="${{ secrets.CODE_SIGN_IDENTITY }}" PROVISIONING_PROFILE="${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}" -derivedDataPath build

      - name: Package the app into a DMG
        run: |
          bash scripts/package-dmg.sh

      - name: ZIP .app archive
        run: |
          cd build/Build/Products/Release
          zip -r Oscar.app.zip Oscar.app

      - name: Upload dmg artifacts
        uses: actions/upload-artifact@v3
        with:
          name: oscar-dmg
          path: oscar-installer.dmg

      - name: Upload app artifacts
        uses: actions/upload-artifact@v3
        with:
          name: oscar-app
          path: build/Build/Products/Release/Oscar.app.zip

  distribute-update:
    needs: build
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download app artifact
        uses: actions/download-artifact@v3
        with:
          name: oscar-app

      - name: Unzip the app artifact
        run: |
          unzip Oscar.app.zip
          ls -la

      - name: Retrieve version from the app
        id: version
        run: |
          VERSION=$(/usr/libexec/PlistBuddy -c "Print CFBundleShortVersionString" Oscar.app/Contents/Info.plist)
          echo "Version: $VERSION"
          echo "::set-output name=version::$VERSION"

      - name: Download dmg artifact
        uses: actions/download-artifact@v3
        with:
          name: oscar-dmg

      - name: Set up AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/AWSCLIV2.pkg" -o "AWSCLIV2.pkg"
          sudo installer -pkg AWSCLIV2.pkg -target /

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region eu-west-1

      - name: Upload DMG to S3
        run: |
          VERSION=$(echo ${{ steps.version.outputs.version }})
          aws s3 cp oscar-installer.dmg ${{ secrets.S3_BUCKET_URL }}/oscar-$VERSION.dmg

      - name: Create local directory
        run: mkdir -p downloaded_files

      - name: Download all files from S3
        run: |
          aws s3 sync ${{ secrets.S3_BUCKET_URL }} downloaded_files/

      - name: Generate appcast
        run: |
          cd downloaded_files
          echo ${{secrets.SPARKLE_PRIVATE_KEY}} | ../scripts/bin/generate_appcast --ed-key-file -

      - name: Upload appcast to S3
        run: |
          aws s3 cp downloaded_files/appcast.xml ${{ secrets.S3_BUCKET_URL }}
