name: Build and Package macOS App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-14

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.0'

    - name: Decode and install certificate
      run: |
        echo "${{ secrets.CERTIFICATE_BASE64 }}" | base64 --decode > /tmp/certificate.p12
        security create-keychain -p "" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "" build.keychain
        security import /tmp/certificate.p12 -k build.keychain -P ${{ secrets.P12_PASSWORD }} -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain
        security list-keychains -s build.keychain

    - name: Install dependencies
      run: |
        brew install create-dmg

    - name: Build the SwiftUI app with code signing
      run: |
        xcodebuild -scheme YourScheme -project Oscar.xcodeproj -configuration Release build CODE_SIGN_IDENTITY="${{ secrets.CODE_SIGN_IDENTITY }}" PROVISIONING_PROFILE="${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}"

    - name: Package the app into a DMG
      run: |
        create-dmg 'build/Release/Oscar.app' --overwrite
